services:
  web:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres_db
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  pg_data:
